# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbef0756cef1f1bc9e416ca3709331490c9cf66e6baf438608aeb833f91c122142855f9d967dad4e951b3933b28e31a69344908b965e08381501023c1e89333a

test:
  secret_key_base: 7813201ea9ad89ba7cf134a1aebf98123f2c450ef213fce1767d8526c2afc40cde1927cfa6141fb97c3ca6597b57c37fbefb69f1327cd90df01b9fddbd14847a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
